-- SQL does not support DEFAULT(CURRENT_DATE)... makes no sense
CREATE TABLE LastVisit (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  day DATE NOT NULL,
  user INT NOT NULL UNIQUE,
  ind TEXT NOT NULL
); 